// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBrYLRca9LhJIWNTzzb0qzjEBDFzTGiPG0",
    authDomain: "menumate-52b6d.firebaseapp.com",
    projectId: "menumate-52b6d",
    storageBucket: "menumate-52b6d.appspot.com",
    messagingSenderId: "170762598738",
    appId: "1:170762598738:web:750c026968904028d6a28b",
    databaseURL: "https://menumate-52b6d-default-rtdb.firebaseio.com",
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlTGLp_SyOfYTaLp5NX9ky1p3OkpY4wgc',
    appId: '1:170762598738:android:be9c2f22fab7c4f2d6a28b',
    messagingSenderId: '170762598738',
    projectId: 'menumate-52b6d',
    databaseURL: 'https://menumate-52b6d-default-rtdb.firebaseio.com',
    storageBucket: 'menumate-52b6d.firebasestorage.app',
  );
}
